apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-adapter.fullname" . }}
  labels:
    {{- include "prometheus-adapter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prometheus-adapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prometheus-adapter.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "prometheus-adapter.serviceAccountName" . }}
      containers:
        - name: prometheus-adapter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --cert-dir=/var/run/serving-cert
            - --config=/etc/adapter/config.yaml
            - --logtostderr=true
            - --metrics-relist-interval=1m
            - --prometheus-url={{ .Values.prometheus.url }}
            - --secure-port={{ .Values.service.targetPort }}
          ports:
            - name: https
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
